#!/bin/bash
set -eu

# Set the database name at here too
# example DB_NAME=bookingDB
DB_NAME=MY_DB_NAME
MIGRATION_NAME=${1:-}

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# Reset the shadow database
encore db reset --shadow $DB_NAME

# GORM executes Go code without initializing Encore when generating migrations,
# so configure the Encore runtime to be aware that this is expected.
export ENCORERUNTIME_NOPANIC=1

# Generate the migration
ATLAS_PATH="C:/Users/cheah/atlas/bin/atlas-windows-amd64-latest.exe"
"$ATLAS_PATH" migrate diff "$MIGRATION_NAME" --env local --dev-url "$(encore db conn-uri --shadow $DB_NAME)&search_path=public"